### ISSUE TITLE
Insufficient buffer clear

### ISSUE THREAD

**Issue by QRiary** [Ikcelaks/qmk_sequence_transform#37]
Buffer doesnt get cleared on oneshot shift press(arguable, but would be nice to have it cleared, or as an option, at least), and what is definitely a bug - it doesnt get cleared on punctuation, I know that we allow it in the rules, so it could be a part of the rule, but thats the point - it only **could**, easiest solution would be to make generator record all the symbols used in the rules and clear buffed if pressed symbol is not in that list, but iirc you didnt like that for some reason, but nevertheless, it should be fixed

**Comment by QRiary** [comment]
Maybe its fine to just give user weak boolean function which would get keycode and return true if buffer has to be cleared for it, idk

**Comment by Ikcelaks** [comment]
Not clearing the buffer on punctuation is intended behavior, because I have several rules that match on punctuation.

Not clearing on one shot shift is a less intentional design decision. Can you give some examples on when that would be good? It would be easy to change.

My next feature is going to be proper word-break support, which would result in the best of both worlds. Punctuation characters will match as themselves first, but also match as a word-break.

Example:
If your rule set is this:
```
,@ -> ,^and
^@ -> for
^* -> the
```
If you type `,@`, you will get `, and`
If you type @` after any other punctuation, you will get the punctuation followed by `for`
If you type `,*`, you will get `,the`

I'm very interested in getting this too!

**Comment by QRiary** [comment]
> Not clearing on one shot shift is a less intentional design decision

Read again, I had it clearing buffer only on press of symbol, not present in **any** rule, it was pretty simple, but custom callback to decide when to clear the buffer would be the best solution I believe, even with your proper word break support, just lets let user decide when to clear the buffer if they want

Oneshot example - I was typing `DoAction` a few days ago, and it(training mode) wanted me to type `a` with magic, which is rather annoying
