### ISSUE TITLE
[CLEANUP] Standardize C/script var/function names

### ISSUE THREAD

**Issue by Ikcelaks** [Ikcelaks/qmk_sequence_transform#54]
Every function needs to be checked and updated to use the new naming conventions.

**Comment by kamih** [comment]
Generally I think it's ok to use 'seq' abbreviation for internal variable/function names, but use 'sequence' for public facing things.

special or magic -> 'sequence token' in descriptions/comments, 'seq_token' for variables
ex: special_key_start -> seq_token_key_start or sequence_token_key_start since it's used in a public API
ex: magic_chars -> seq_tokens or seq_token_symbols
ex: context_match_len -> seq_match_len

Oh and we should take this opportunity to rename `key_buffer->size` to `key_buffer->capacity`, and `context_len` to `size`.
(And also rename the file to key_buffer.c/h to match other names.)
