### ISSUE TITLE
[CLEANUP] use `const` wherever possible

### ISSUE THREAD

**Issue by Ikcelaks** [Ikcelaks/qmk_sequence_transform#56]
If a parameter or local var can be `const` it should be `const`, or `* const`, or `const * const`

**Comment by kamih** [comment]
Agreed. `const *` helps us see what function params are input vs potential output, and prevents us from accidentally writing to things we shouldn't be writing to.
And since we can't have private class members in C, having struct member pointers as `const * const` is an alternative that makes sure we don't change these member vars.
